export const state = {
    "Andaman and Nicobar Islands": [
      "Port Blair",
      "South Andaman",
      "North And Middle Andaman"
    ],
    "Andhra Pradesh": [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Kakinada",
      "Rajahmundry",
      "Tirupati",
      "Kadapa",
      "Anantapur"
    ],
    "Arunachal Pradesh": [
      "Itanagar",
      "Naharlagun",
      "Pasighat",
      "Ziro",
      "Tawang",
      "Bomdila",
      "Khonsa",
      "Tezu",
      "Anini",
      "Roing"
    ],
    "Assam": [
      "Guwahati",
      "Silchar",
      "Dibrugarh",
      "Jorhat",
      "Nagaon",
      "Tinsukia",
      "Tezpur",
      "Karimganj",
      "Sivasagar",
      "Bongaigaon"
    ],
    "Bihar": [
      "Patna",
      "Gaya",
      "Bhagalpur",
      "Muzaffarpur",
      "Purnia",
      "Darbhanga",
      "Bihar Sharif",
      "Arrah",
      "Begusarai",
      "Katihar"
    ],
    "Chandigarh": [
      "Chandigarh"
    ],
    "Chhattisgarh": [
      "Raipur",
      "Bhilai",
      "Bilaspur",
      "Korba",
      "Rajnandgaon",
      "Raigarh",
      "Jagdalpur",
      "Ambikapur",
      "Dhamtari",
      "Mahasamund"
    ],
    "Dadra and Nagar Haveli and Daman and Diu": [
      "Daman",
      "Diu",
      "Silvassa"
    ],
    "Delhi": [
      "New Delhi",
      "North Delhi",
      "South Delhi",
      "East Delhi",
      "West Delhi",
      "Central Delhi",
      "North East Delhi",
      "North West Delhi",
      "South West Delhi",
      "South East Delhi"
    ],
    "Goa": [
      "Panaji",
      "Mormugao",
      "Margao",
      "Mapusa",
      "Ponda",
      "Vasco Da Gama",
      "Bicholim",
      "Curchorem",
      "Cuncolim",
      "Quepem"
    ],
    "Gujarat": [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Junagadh",
      "Gandhinagar",
      "Nadiad",
      "Mehsana"
    ],
    "Haryana": [
      "Faridabad",
      "Gurgaon",
      "Panipat",
      "Ambala",
      "Yamunanagar",
      "Rohtak",
      "Hisar",
      "Karnal",
      "Sonipat",
      "Panchkula"
    ],
    "Himachal Pradesh": [
      "Shimla",
      "Solan",
      "Dharamshala",
      "Mandi",
      "Kullu",
      "Chamba",
      "Bilaspur",
      "Nahan",
      "Una",
      "Palampur"
    ],
    "Jammu and Kashmir": [
      "Srinagar",
      "Jammu",
      "Anantnag",
      "Baramulla",
      "Kathua",
      "Sopore",
      "Bandipore",
      "Udhampur",
      "Kupwara",
      "Rajouri"
    ],
    "Jharkhand": [
      "Ranchi",
      "Jamshedpur",
      "Dhanbad",
      "Bokaro",
      "Deoghar",
      "Phusro",
      "Hazaribagh",
      "Giridih",
      "Ramgarh",
      "Medininagar"
    ],
    "Karnataka": [
      "Bangalore",
      "Hubli",
      "Mangalore",
      "Belgaum",
      "Gulbarga",
      "Davanagere",
      "Bellary",
      "Bangalore Rural",
      "Bidar",
      "Shimoga"
    ],
    "Kerala": [
      "Thiruvananthapuram",
      "Kochi",
      "Kozhikode",
      "Kollam",
      "Thrissur",
      "Alappuzha",
      "Palakkad",
      "Malappuram",
      "Kannur",
      "Manjeri"
    ],
    "Ladakh": [
      "Leh",
      "Kargil"
    ],
    "Lakshadweep": [
      "Kavaratti",
      "Agatti Island"
    ],
    "Madhya Pradesh": [
      "Indore",
      "Bhopal",
      "Jabalpur",
      "Gwalior",
      "Ujjain",
      "Sagar",
      "Dewas",
      "Satna",
      "Ratlam",
      "Rewa"
    ],
    "Maharashtra": [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Thane",
      "Nashik",
      "Kalyan-Dombivali",
      "Vasai-Virar",
      "Aurangabad",
      "Navi Mumbai",
      "Solapur"
    ],
    "Manipur": [
      "Imphal",
      "Thoubal",
      "Lilong",
      "Kakching",
      "Ukhrul",
      "Wangjing",
      "Churachandpur",
      "Sugnu",
      "Nambol",
      "Mayang Imphal"
    ],
    "Meghalaya": [
      "Shillong",
      "Tura",
      "Nongstoin",
      "Nongpoh",
      "Williamnagar",
      "Mairang",
      "Jowai",
      "Baghmara",
      "Resubelpara",
      "Khliehriat"
    ],
    "Mizoram": [
      "Aizawl",
      "Lunglei",
      "Saiha",
      "Champhai",
      "Serchhip",
      "Kolasib",
      "Khawzawl",
      "Hnahthial",
      "Demagiri",
      "Mamit"
    ],
    "Nagaland": [
      "Dimapur",
      "Kohima",
      "Mokokchung",
      "Tuensang",
      "Wokha",
      "Phek",
      "Zunheboto",
      "Mon",
      "Chumukedima",
      "Longleng"
    ],
    "Odisha": [
      "Bhubaneswar",
      "Cuttack",
      "Rourkela",
      "Berhampur",
      "Sambalpur",
      "Puri",
      "Balasore",
      "Bhadrak",
      "Baripada",
      "Jharsuguda"
    ],
    "Puducherry": [
      "Puducherry",
      "Karaikal",
      "Mahe",
      "Yanam"
    ],
    "Punjab": [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Hoshiarpur",
      "Mohali",
      "Batala",
      "Pathankot",
      "Moga"
    ],
    "Rajasthan": [
      "Jaipur",
      "Jodhpur",
      "Kota",
      "Bikaner",
      "Ajmer",
      "Udaipur",
      "Bhilwara",
      "Alwar",
      "Bharatpur",
      "Sikar"
    ],
    "Sikkim": [
      "Gangtok",
      "Namchi",
      "Mangan",
      "Gyalshing",
      "Ravangla",
      "Singtam",
      "Naya Bazar",
      "Jorethang",
      "Rinchenpong",
      "Rangpo"
    ],
    "Tamil Nadu": [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Tiruppur",
      "Erode",
      "Vellore",
      "Thoothukkudi",
      "Tirunelveli"
    ],
    "Telangana": [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Khammam",
      "Karimnagar",
      "Ramagundam",
      "Mahabubnagar",
      "Nalgonda",
      "Adilabad",
      "Suryapet"
    ],
    "Tripura": [
      "Agartala",
      "Udaipur",
      "Dharmanagar",
      "Kailasahar",
      "Ambassa",
      "Khowai",
      "Belonia",
      "Teliamura",
      "Santirbazar",
      "Sonamura"
    ],
    "Uttar Pradesh": [
      "Lucknow",
      "Kanpur",
      "Ghaziabad",
      "Agra",
      "Varanasi",
      "Allahabad",
      "Meerut",
      "Bareilly",
      "Aligarh",
      "Moradabad"
    ],
    "Uttarakhand": [
      "Dehradun",
      "Haridwar",
      "Roorkee",
      "Haldwani",
      "Rudrapur",
      "Kashipur",
      "Rishikesh",
      "Pithoragarh",
      "Ramnagar",
      "Kotdwara"
    ],
    "West Bengal": [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Asansol",
      "Siliguri",
      "Maheshtala",
      "Rajpur Sonarpur",
      "South Dumdum",
      "Gopalpur",
      "Bhatpara"
    ]
  }
  
  